backend:
  name: git-gateway
  branch: no_webpack

publish_mode: editorial_workflow
media_folder: assets/images/uploads

collections:
  - name: locations
    label: Map Markers
    folder: contents/_locations
    create: true
    slug: "{{slug}}"
    fields:
    - { name: "layout", widget: "hidden", default: "page" }
    - { label: "Title", name: "marker_title", widget: "string" }
    - { label: "Popup Code", name: "marker_popup_html", widget: "code", default_language: "html", output_code_only: true }
    - name: location
      label: Coordinates
      widget: object
      collapsed: false
      fields:
        - { label: "Latitude", name: "latitude", widget: "number", valueType: "float" }
        - { label: "Longitude", name: "longitude", widget: "number", valueType: "float" }
  - name: posts
    label: Blog Posts
    folder: contents/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tag", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - label: Image Layout
        name: image_side
        widget: select
        options:
        - { label: "Left", value: "left" }
        - { label: "Right", value: "right" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: slides
    label: Carousel
    folder: contents/_slides
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "slide" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Background Image", name: "background", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }

