backend:
  name: git-gateway
  branch: no_webpack

publish_mode: editorial_workflow
media_folder: assets/images/uploads

collections:
  - name: pages
    label: Pages
    files:
      - name: locations
        label: Map Markers
        file: _data/locations.yml
        create: true
        format: yml
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Url", name: "url", widget: "string" }
          - label: Location
            name: location
            widget: object
            collapsed: false
            fields:
              - { label: "Latitude", name: "latitude", widget: "string" }
              - { label: "Longitude", name: "longitude", widget: "string" }
  - name: posts
    label: Blog Posts
    folder: contents/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tag", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: slides
    label: Carousel
    folder: contents/_slides
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "slide" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Background Image", name: "background", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }

